name: Release assets
permissions: write-all
on:
  release:
    types: [ prereleased, published ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      IS_VALID_TAG: ${{ steps.check.outputs.IS_VALID_TAG }}
    steps:
      - name: check tag version
        id: check
        run: |
          REF=${{ github.ref }}
          if [[ "$REF" =~ refs/tags/v[0-9]+.[0-9]+.[0-9]+.* ]]; then
            IS_VALID_TAG=true
          else
              echo "Expected refs of the form 'refs/tags/v-<major-version>.<minor-version>.<patch-version>' but got '$REF'"
              IS_VALID_TAG=false
          fi
          echo "IS_VALID_TAG=$IS_VALID_TAG"
          echo "IS_VALID_TAG=$IS_VALID_TAG" >> "$GITHUB_OUTPUT"
  build-and-upload:
    runs-on: ubuntu-latest
    needs: prepare
    if: needs.prepare.outputs.IS_VALID_TAG
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean package -DskipTests
      - uses: AButler/upload-release-assets@v3.0
        with:
          files: 'target/github-ations-*.*.jar'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
